default_ssh_username: root
default_ssh_key_path: ~/.ssh/id_rsa
servers:
  10.0.11.1:

    libvirt_uri: "qemu+ssh://root@10.0.11.1/system"
  10.0.12.1:
    libvirt_uri: "qemu+ssh://root@10.0.12.1/system"
  10.0.0.4:

    libvirt_uri: "qemu+ssh://root@10.0.0.4/system"
  10.0.6.17:
    libvirt_uri: "qemu+ssh://root@10.0.16.17/system"
  10.0.2.254:
    libvirt_uri: "qemu+ssh://root@10.0.2.254/system"
  10.0.10.1:
    libvirt_uri: "qemu+ssh://root@10.0.10.1/system"
    ssh_port: 16666
